### ISSUE TITLE
stop recording

### ISSUE THREAD

**Issue by sebastianhenaosanta** [caizhengxin/python-libpcap#12]
Hey caizhengxin i hope you're ok, this not an issue this more like a question.
 i would like to know how to stop recording pcap packages whetn the flag count is equal to -1 in sniffing mode.

sometimes when i open the file in wireshark, it says that a package in the middle is  either corrupted or uncompleted.

Thanks

**Comment by caizhengxin** [comment]
> Hey caizhengxin i hope you're ok, this not an issue this more like a question.
> i would like to know how to stop recording pcap packages whetn the flag count is equal to -1 in sniffing mode.
> 
> sometimes when i open the file in wireshark, it says that a package in the middle is either corrupted or uncompleted.
> 
> Thanks

Hi, Is there a pcap example？
