### ISSUE TITLE
Byte offset

### ISSUE THREAD

**Issue by sebastianhenaosanta** [caizhengxin/python-libpcap#13]
is it possible to get byte offset of each package with python-libpcap?, as it is proposed in this link 
[](https://stackoverflow.com/questions/11681665/using-libpcap-is-there-a-way-to-determine-the-file-offset-of-a-captured-packet)

**Comment by caizhengxin** [comment]
> is it possible to get byte offset of each package with python-libpcap?, as it is proposed in this link

Hi, I don't quite understand what it means，packet length？

**Comment by caizhengxin** [comment]
> No, byte offset means the position in bytes of each package inside the binary file. Having this a user can open the file and point to any package without iterating again and again.

Since pcap has specifications, byte offset is not easy to calculate, you can decompose the pcap file
