### ISSUE TITLE
Install issue with python3.10

### ISSUE THREAD

**Issue by lgandx** [caizhengxin/python-libpcap#15]
Hello, 

Since python3.10, I'm unable to install this library on a debian based OS.
Installation of the library works without any problem:
`sudo apt-get install libpcap-dev && pip3 install Cython && pip3 install python-libpcap`

however, when calling the modules, a cython error occurs:
`>>> import pylibpcap as pcap`
`>>> from pylibpcap.pcap import rpcap`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python3.10/dist-packages/pylibpcap/pcap.py", line 6, in <module>`
`    from pylibpcap.base import Sniff, LibPcap`
`ImportError: /usr/local/lib/python3.10/dist-packages/pylibpcap/base.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send`
>>> 

Look like several other libraries had this specific issue with Cython on python 3.10
 
Cheers,

**Comment by caizhengxin** [comment]
> ImportError: /usr/local/lib/python3.10/dist-packages/pylibpcap/base.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send

https://github.com/cython/cython/issues/3876

**Comment by lgandx** [comment]
Meanwhile there is a workaround: https://github.com/lgandx/PCredz/issues/48#issuecomment-1183750043
