### ISSUE TITLE
Python 3.10 + Cython: undefined symbol: _PyGen_Send

### ISSUE THREAD

**Issue by linuxkd** [caizhengxin/python-libpcap#16]
### Python
Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0] on linux

### Cython

```
python -c "from Cython.Compiler.Version import version; print (version)"
3.0.0a11
```

### python-libpcap
```
python -m pip install python-libpcap
Defaulting to user installation because normal site-packages is not writeable
Collecting python-libpcap
  Using cached python_libpcap-0.4.0-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: Cython>=0.29.13 in /usr/local/lib/python3.10/dist-packages/Cython-3.0.0a11-py3.10-linux-x86_64.egg (from python-libpcap) (3.0.0a11)
Installing collected packages: python-libpcap
  WARNING: The scripts libpcap-capture, libpcap-merge, libpcap-read and libpcap-write are installed in '/home/swag/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed python-libpcap-0.4.0
```

## Error importing rpcap
```
Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylibpcap as pcap
>>> from pylibpcap.pcap import rpcap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/pylibpcap/pcap.py", line 6, in <module>
    from pylibpcap.base import Sniff, LibPcap
ImportError: /home/user/.local/lib/python3.10/site-packages/pylibpcap/base.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

### Notes
When trying to import rpcap we received an import error related to Cython undefined symbol. I have found multiple issues from upstream with this error, however they have implemented fixes in the latest versions of Cython specifically for this issue. However, the issue still remains in python-libpcap.
https://github.com/cython/cython/issues/3876

It looks like Python 3.10 has a new procedure to replace _PyGen_Send as commented on here:
https://github.com/cython/cython/issues/3876#issuecomment-706674249

Code was committed upstream in Cython to change from _PyGen_Send to PyIterSend here:
https://github.com/cython/cython/pull/3921/commits/5fec31d6155397ad6e8ef76bf1477c9e30c08031

## Working method
If I clone this project and run setup it works properly. The issue appears to be with pip installations.
```
git clone https://github.com/caizhengxin/python-libpcap.git
sudo python setup.py install
```

```
python
Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylibpcap
>>> from pylibpcap.pcap import rpcap
>>>
```

**Comment by linuxkd** [comment]
@caizhengxin, any chance you can address this? I believe you likely only need to issue a new build via pip targeting a later version of Cython that has the upstream fixes in place, no code changes are needed. 

Thank you for all your hard work either way, it is appreciated!

**Comment by caizhengxin** [comment]
> @caizhengxin, any chance you can address this? I believe you likely only need to issue a new build via pip targeting a later version of Cython that has the upstream fixes in place, no code changes are needed.
> 
> Thank you for all your hard work either way, it is appreciated!

Sorry, update v0.4.1
