### ISSUE TITLE
Large delay with sniff() function after updating to Ubuntu 19.10

### ISSUE THREAD

**Issue by lken274** [caizhengxin/python-libpcap#2]
I've been using this library for a while to read live networking traffic on Ubuntu 16.04 LTS.
After updating to Ubuntu 19.10, there is a 5+ second latency between when a packet arrives (shown in tcpdump) and when sniff() returns.
`for plen, t, buf in sniff("wlo1", filters="src host <IP>", count=-1, promisc=1, out_file=""):`

WiFi Card: Cannon Point-LP CNVi [Wireless-AC]
HP Pavilion Laptop 14-ce2xxx

**Comment by lken274** [comment]
My current work-around is to rebuild using "immediate mode" in base.pyx

`
self.handler = pcap_create(self.iface, self.errbuf)<br/>
        pcap_set_snaplen(self.handler, snaplen)
        pcap_set_promisc(self.handler, promisc)
        pcap_set_timeout(self.handler, 0)
        pcap_set_immediate_mode(self.handler, 1)
        pcap_activate(self.handler)
        # self.handler = pcap_open_live(self.iface, snaplen, promisc, 0, self.errbuf)
`

**Comment by caizhengxin** [comment]
> My current work-around is to rebuild using "immediate mode" in base.pyx
> 
> ```
> self.handler = pcap_create(self.iface, self.errbuf)
> pcap_set_snaplen(self.handler, snaplen)
> pcap_set_promisc(self.handler, promisc)
> pcap_set_timeout(self.handler, 0)
> pcap_set_immediate_mode(self.handler, 1)
> pcap_activate(self.handler)
> # self.handler = pcap_open_live(self.iface, snaplen, promisc, 0, self.errbuf)
> ```
> 
> Here's the .so file for anyone that wants it.
> 
> [base.zip](https://github.com/caizhengxin/python-libpcap/files/4113273/base.zip)

Sorry, I ca n’t see it in time. Due to the recent Spring Festival, the code cannot be updated temporarily. Thank you for your suggestion.

**Comment by FreibergVlad** [comment]
The same issue on Manjaro. Kernel version: 5.4.24-1

**Comment by alexhartl** [comment]
While @lken274's suggestion works, ae78f852f84140bb4307c3e931ec31fa116f2107 does **not** fix the issue (at least not on my system). The reason probably is that you have to call `pcap_set_immediate_mode()` before `pcap_activate()` which is called by `pcap_open_live()`.

**Comment by caizhengxin** [comment]
> While @lken274's suggestion works, [ae78f85](https://github.com/caizhengxin/python-libpcap/commit/ae78f852f84140bb4307c3e931ec31fa116f2107) does **not** fix the issue (at least not on my system). The reason probably is that you have to call `pcap_set_immediate_mode()` before `pcap_activate()` which is called by `pcap_open_live()`.

Thank you for your suggestion, I don't have that system test
