### ISSUE TITLE
wpcap error (python-libpcap   0.5.1)

### ISSUE THREAD

**Issue by smilesmall** [caizhengxin/python-libpcap#21]
from pylibpcap import wpcap

buf = b'\x00\xc0\x9f2A\x8c\x00\xe0\x18\xb1\x0c\xad\x08\x00E\x00\x008' \
        b'\x00\x00@\x00@\x11eG\xc0\xa8\xaa\x08\xc0\xa8\xaa\x14\x80\x1b' \
        b'\x005\x00$\x85\xed\x102\x01\x00\x00\x01\x00\x00\x00\x00\x00' \
        b'\x00\x06google\x03com\x00\x00\x10\x00\x01'

# ok
wpcap([buf]*20, "pcap.pcap")   # 20
wpcap([buf]*20, "pcap.pcap")   # 40

# error
wpcap([buf]*100, "pcap2.pcap")  # 100 
wpcap([buf]*100, "pcap2.pcap")   #  error

**Comment by caizhengxin** [comment]
> from pylibpcap import wpcap
> 
> buf = b'\x00\xc0\x9f2A\x8c\x00\xe0\x18\xb1\x0c\xad\x08\x00E\x00\x008' b'\x00\x00@\x00@\x11eG\xc0\xa8\xaa\x08\xc0\xa8\xaa\x14\x80\x1b' b'\x005\x00$\x85\xed\x102\x01\x00\x00\x01\x00\x00\x00\x00\x00' b'\x00\x06google\x03com\x00\x00\x10\x00\x01'
> 
> # ok
> wpcap([buf]*20, "pcap.pcap") # 20 wpcap([buf]*20, "pcap.pcap") # 40
> 
> # error
> wpcap([buf]*100, "pcap2.pcap") # 100 wpcap([buf]*100, "pcap2.pcap") # error

Hi, thanks for the feedback, it has been fixed in v0.5.2.
