### ISSUE TITLE
Trying pcapkit.extract method getting this error

### ISSUE THREAD

**Issue by adityasriv22** [caizhengxin/python-libpcap#3]
Traceback (most recent call last):
  File "dpkt_parse.py", line 4, in <module>
    pcapkit.extract(fin=file, fout='out.plist', format='plist', store=False)
TypeError: object_hook() missing 1 required positional argument: 'o'

**Comment by caizhengxin** [comment]
> Traceback (most recent call last):
> File "dpkt_parse.py", line 4, in
> pcapkit.extract(fin=file, fout='out.plist', format='plist', store=False)
> TypeError: object_hook() missing 1 required positional argument: 'o'

Your problem doesn't seem to be here, it may be another library.
