### ISSUE TITLE
Packets...

### ISSUE THREAD

**Issue by Kevin-Prichard** [caizhengxin/python-libpcap#4]
Not an issue so much as a question... `rpcap()` returns a raw bytes for the packet ... is there a companion module you'd recommend to provide structure/properties, or an object interface, to those packets? The raw blob ain't exactly self-explanatory, unless I'm missing something about this module.

**Comment by caizhengxin** [comment]
Hi, structure/properties？parse raw packet?

Kevin Prichard <notifications@github.com> 于2020年5月24日周日 上午5:35写道：

**Comment by caizhengxin** [comment]
> Not an issue so much as a question... `rpcap()` returns a raw bytes for the packet ... is there a companion module you'd recommend to provide structure/properties, or an object interface, to those packets? The raw blob ain't exactly self-explanatory, unless I'm missing something about this module.

Hi, structure/properties is parse raw packet?
