### ISSUE TITLE
pyinstaller is not working with this library

### ISSUE THREAD

**Issue by sebastianhenaosanta** [caizhengxin/python-libpcap#5]
This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.

are there some shortcuts to make it possible ?

**Comment by caizhengxin** [comment]
> This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> 
> are there some shortcuts to make it possible ?

Hi, have error and os version?

**Comment by sebastianhenaosanta** [comment]
> > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > are there some shortcuts to make it possible ?
> 
> Hi, have error and os version

 hey, i'm using ubuntu 18.04 and this is the error:
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "pylibpcap/pcap.py", line 6, in <module>
  File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '__reduce_cython__'
[12867] Failed to execute script test

**Comment by caizhengxin** [comment]
> > > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > > are there some shortcuts to make it possible ?
> > 
> > 
> > Hi, have error and os version
> 
> hey, i'm using ubuntu 18.04 and this is the error:
> Traceback (most recent call last):
> File "test.py", line 1, in
> File "frozen importlib._bootstrap>", line 971, in _find_and_load
> File "frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> File "frozen importlib._bootstrap>", line 665, in _load_unlocked
> File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
> exec(bytecode, module.**dict**)
> File "pylibpcap/pcap.py", line 6, in module>
> File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
> AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '**reduce_cython**'
> [12867] Failed to execute script test

dist/xxx/pylibpcap, Not py file

**Comment by sebastianhenaosanta** [comment]
> > > > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > > > are there some shortcuts to make it possible ?
> > > 
> > > 
> > > Hi, have error and os version
> > 
> > 
> > hey, i'm using ubuntu 18.04 and this is the error:
> > Traceback (most recent call last):
> > File "test.py", line 1, in
> > File "frozen importlib._bootstrap>", line 971, in _find_and_load
> > File "frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> > File "frozen importlib._bootstrap>", line 665, in _load_unlocked
> > File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
> > exec(bytecode, module.**dict**)
> > File "pylibpcap/pcap.py", line 6, in module>
> > File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
> > AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '**reduce_cython**'
> > [12867] Failed to execute script test
> 
> dist/xxx/pylibpcap, Not py file

the command that i'm using is this:
pyinstaller test.py 
and then pyinstaller makes the compilation without errors, but when i;m going to execute the the file i got that error

**Comment by caizhengxin** [comment]
> > > > > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > > > > are there some shortcuts to make it possible ?
> > > > 
> > > > 
> > > > Hi, have error and os version
> > > 
> > > 
> > > hey, i'm using ubuntu 18.04 and this is the error:
> > > Traceback (most recent call last):
> > > File "test.py", line 1, in
> > > File "frozen importlib._bootstrap>", line 971, in _find_and_load
> > > File "frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> > > File "frozen importlib._bootstrap>", line 665, in _load_unlocked
> > > File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
> > > exec(bytecode, module.**dict**)
> > > File "pylibpcap/pcap.py", line 6, in module>
> > > File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
> > > AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '**reduce_cython**'
> > > [12867] Failed to execute script test
> > 
> > 
> > dist/xxx/pylibpcap, Not py file
> 
> the command that i'm using is this:
> pyinstaller test.py
> and then pyinstaller makes the compilation without errors, but when i;m going to execute the the file i got that error and i don't know what's the problem.

**Comment by caizhengxin** [comment]
> > > > > > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > > > > > are there some shortcuts to make it possible ?
> > > > > 
> > > > > 
> > > > > Hi, have error and os version
> > > > 
> > > > 
> > > > hey, i'm using ubuntu 18.04 and this is the error:
> > > > Traceback (most recent call last):
> > > > File "test.py", line 1, in
> > > > File "frozen importlib._bootstrap>", line 971, in _find_and_load
> > > > File "frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> > > > File "frozen importlib._bootstrap>", line 665, in _load_unlocked
> > > > File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
> > > > exec(bytecode, module.**dict**)
> > > > File "pylibpcap/pcap.py", line 6, in module>
> > > > File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
> > > > AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '**reduce_cython**'
> > > > [12867] Failed to execute script test
> > > 
> > > 
> > > dist/xxx/pylibpcap, Not py file
> > 
> > 
> > the command that i'm using is this:
> > pyinstaller test.py
> > and then pyinstaller makes the compilation without errors, but when i;m going to execute the the file i got that error and i don't know what's the problem.

Sorry,  Accidentally closed

> > > > > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > > > > are there some shortcuts to make it possible ?
> > > > 
> > > > 
> > > > Hi, have error and os version
> > > 
> > > 
> > > hey, i'm using ubuntu 18.04 and this is the error:
> > > Traceback (most recent call last):
> > > File "test.py", line 1, in
> > > File "frozen importlib._bootstrap>", line 971, in _find_and_load
> > > File "frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> > > File "frozen importlib._bootstrap>", line 665, in _load_unlocked
> > > File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
> > > exec(bytecode, module.**dict**)
> > > File "pylibpcap/pcap.py", line 6, in module>
> > > File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
> > > AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '**reduce_cython**'
> > > [12867] Failed to execute script test
> > 
> > 
> > dist/xxx/pylibpcap, Not py file
> 
> the command that i'm using is this:
> pyinstaller test.py
> and then pyinstaller makes the compilation without errors, but when i;m going to execute the the file i got that error and i don't know what's the problem.

Sorry, Accidentally closed

**Comment by caizhengxin** [comment]
> > > > > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > > > > are there some shortcuts to make it possible ?
> > > > 
> > > > 
> > > > Hi, have error and os version
> > > 
> > > 
> > > hey, i'm using ubuntu 18.04 and this is the error:
> > > Traceback (most recent call last):
> > > File "test.py", line 1, in
> > > File "frozen importlib._bootstrap>", line 971, in _find_and_load
> > > File "frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> > > File "frozen importlib._bootstrap>", line 665, in _load_unlocked
> > > File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
> > > exec(bytecode, module.**dict**)
> > > File "pylibpcap/pcap.py", line 6, in module>
> > > File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
> > > AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '**reduce_cython**'
> > > [12867] Failed to execute script test
> > 
> > 
> > dist/xxx/pylibpcap, Not py file
> 
> the command that i'm using is this:
> pyinstaller test.py
> and then pyinstaller makes the compilation without errors, but when i;m going to execute the the file i got that error and i don't know what's the problem.

Add -D, see dist/xxx/pylibpcap, Not py file

**Comment by caizhengxin** [comment]
> > > > > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > > > > are there some shortcuts to make it possible ?
> > > > 
> > > > 
> > > > Hi, have error and os version
> > > 
> > > 
> > > hey, i'm using ubuntu 18.04 and this is the error:
> > > Traceback (most recent call last):
> > > File "test.py", line 1, in
> > > File "frozen importlib._bootstrap>", line 971, in _find_and_load
> > > File "frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> > > File "frozen importlib._bootstrap>", line 665, in _load_unlocked
> > > File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
> > > exec(bytecode, module.**dict**)
> > > File "pylibpcap/pcap.py", line 6, in module>
> > > File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
> > > AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '**reduce_cython**'
> > > [12867] Failed to execute script test
> > 
> > 
> > dist/xxx/pylibpcap, Not py file
> 
> the command that i'm using is this:
> pyinstaller test.py
> and then pyinstaller makes the compilation without errors, but when i;m going to execute the the file i got that error and i don't know what's the problem.

sudo cp /usr/local/lib/python3.6/dist-packages/pylilbpcap/* xxx/dist/xxx/pylibpcap, run ok

**Comment by sebastianhenaosanta** [comment]
> > > > > > This is not issue it's more like a question. I'm trying to make an executable of this library with pyinstaller but by the moment is not working.
> > > > > > are there some shortcuts to make it possible ?
> > > > > 
> > > > > 
> > > > > Hi, have error and os version
> > > > 
> > > > 
> > > > hey, i'm using ubuntu 18.04 and this is the error:
> > > > Traceback (most recent call last):
> > > > File "test.py", line 1, in
> > > > File "frozen importlib._bootstrap>", line 971, in _find_and_load
> > > > File "frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> > > > File "frozen importlib._bootstrap>", line 665, in _load_unlocked
> > > > File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
> > > > exec(bytecode, module.**dict**)
> > > > File "pylibpcap/pcap.py", line 6, in module>
> > > > File "pylibpcap/base.pyx", line 20, in init pylibpcap.base
> > > > AttributeError: type object 'pylibpcap.base.BasePcap' has no attribute '**reduce_cython**'
> > > > [12867] Failed to execute script test
> > > 
> > > 
> > > dist/xxx/pylibpcap, Not py file
> > 
> > 
> > the command that i'm using is this:
> > pyinstaller test.py
> > and then pyinstaller makes the compilation without errors, but when i;m going to execute the the file i got that error and i don't know what's the problem.
> 
> sudo cp /usr/local/lib/python3.6/dist-packages/pylilbpcap/* xxx/dist/xxx/pylibpcap, run ok

Thank you very much,  it works perfectly
