### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by mircusmaa** [caizhengxin/python-libpcap#6]
hey I wrote a simpel demo to test the performance of reading&sending pcap likes:

for _, t, pkt in rpcap("/data/xxx.pcap"):
    send_packet("eth0", pkt)

I think I read memory increase when I am running demo (in htop).
valgrind also shows the memory leak. 

but I didn't figure out where this memory leak from

**Comment by caizhengxin** [comment]
> hey I wrote a simpel demo to test the performance of reading&sending pcap likes:
> 
> for _, t, pkt in rpcap("/data/xxx.pcap"):
> send_packet("eth0", pkt)
> 
> I think I read memory increase when I am running demo (in htop).
> valgrind also shows the memory leak.
> 
> but I didn't figure out where this memory leak from

Hi, send_packet not free memory

**Comment by mircusmaa** [comment]
yeah I just figured it out today. I rewrite some functions. Nice code bro btw!
