### ISSUE TITLE
Support for the stats function in libcap?

### ISSUE THREAD

**Issue by OzzyKampha** [caizhengxin/python-libpcap#9]
Could you implement the status function in libcap, so it is possible to get stats out of the sniffing?

**Comment by caizhengxin** [comment]
> Could you implement the status function in libcap, so it is possible to get stats out of the sniffing?

Hi, you want to capture packets at the end, show stats?

**Comment by OzzyKampha** [comment]
I want to get ack,dropped stats from libcap on the sniffed interface, so you can check if the Python process get all the packets

**Comment by caizhengxin** [comment]
> I want to get ack,dropped stats from libcap on the sniffed interface, so you can check if the Python process get all the packets
> 
> stats returns statistics on the current capture as a tuple (recv, drop, ifdrop)

OK, Thanks for your suggestion, develop has been implemented.

**Comment by OzzyKampha** [comment]
Thanks:) 

PS: Do you have any good resources about cython?

**Comment by caizhengxin** [comment]
> Thanks, when will be pushed to master/pip
> 
> PS: Do you have any good resources about cython?

I need to change something, merge master/pip tomorrow.
PS: Official document, http://docs.cython.org/en/latest/

**Comment by caizhengxin** [comment]
> Thanks, when will be pushed to master/pip
> 
> PS: Do you have any good resources about cython?

Okay, See ``v0.4.0``

**Comment by OzzyKampha** [comment]
Very good implement
